### PR TITLE
Feature/autopep8 entire repo

### PR DESCRIPTION
**Pull request by cdpierse**

### CODE REVIEW

**Comment by cdpierse** [comment]
- Please feel free not to merge this but since we discussed using pycodestyle/pep8 as default formatter I thought I'd go ahead and apply it recursively to the entire repo and see what it changed.
- From what I can see it's mostly just whitespace removal and a couple of hanging lines it has changed.
- To run the same command on your machine just type `autopep8 --in-place --recursive .`

**Comment by Voyz** [comment]
Cool! Looks good to me, just thinking about merge conflicts with the existing branches. Maybe lets wait to have the tags #14  reviewed and merged and then run through this? I think no other PRs should have heavy conflicts atm, right?

**Comment by Voyz** [comment]
Yeah, so I'd say maybe re-running autopep8 on the current dev, then committing and merging this afterwards would be a good idea? There's no dangling PRs that would conflict heavily.

**Comment by cdpierse** [comment]
Yeah so that was exactly my thought, I'm going to wait until all current PR's are merged and then run again.

**Review by Voyz — APPROVED** [review]
All good 👍

**Comment by Voyz** [comment]
Just for future reference - autopep caused some import issues, so we decided to manually fix these and merge this branch either way to have pep already in the repository for most of the files. We will revisit auto pep in the next release.

**Pull request merged**
