### PR TITLE
Feature/python version support

### PR DESCRIPTION
**Pull request by cdpierse**
- Adds `python_requires` param to the package setup script. 
- This will actually block installs through pypi that are not explicitly found in our requires string. So there is certainly a benefit here in adding some sort of install test to check for expected blocking and non-blocking behaviour, but how exactly I'm not sure.

### CODE REVIEW

**Comment by Voyz** [comment]
Okay cool! Now that I read through what you wrote I'm thinking: if Databay would work ok with version 3.6 and below, is it a good idea to prevent installs on these? I suppose it would be a good task to run Databay on these versions and verify up to which we have support. But even for now maybe let's just leave it open to any versions and just write which versions are officially tested against in the Readme? 

I'll add a task for the version testing, but what do you say about not preventing installs on previous versions yet? Is there a way to say 'suggested version' in the setup.py, rather than required?

**Review by Voyz — COMMENTED** [review]
Looking good! Love how well formatted in code it is! A few of suggestions:

1. I'd write the first entry as `<=3.6` rather than `3.6` to indicate that lower versions aren't supported either.
1. Do we not support 3.9? I'd assume Databay should work there out of the box? Maybe worth trying it on 3.9 at this stage already?
1. Would it maybe work better as horizontal? Now there's all that white space on the right that we could nicely fill in.
image
1. I'd suggest putting it a little lower down the readme, as I feel this info is of lower importance. I do this with the assumption that majority of our uses will be supported (we can probably get over the 3.6 issues), therefore wouldn't need to look at this chart. My suggestion would be to create a new subsection of the Readme called 'Supported Version' or whatever would fit, and put it there, say between Overview and Community Contributions. Feel free to disagree with this suggestion and discuss tho! 👍

**Comment by cdpierse** [comment]
Thanks for the feedback! You were right on all of those points.
1. I've updated table to show that we support 3.6 up to 3.9. Ran tests on my machine with 3.9 and all passed. I have 3.6 ticked as working as I know #21 corrects patches support for 3.6. 
2. Table is now horizontal, definitely a better use of space. 
3. Have moved it between Overview and community contributions.

**Comment by Voyz** [comment]
Nice job mate! Ready to merge 😊

**Pull request merged**
